import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadOracleProfile } from './profile.mjs';

const root=resolve(fileURLToPath(new URL('../..',import.meta.url)));
const pinned=loadOracleProfile();
assert.equal(pinned.id,'ts7');
assert.equal(pinned.version,'7.0.2');
assert.equal(pinned.npmSpec,'typescript@7.0.2');
assert.equal(pinned.executable,'tsc');
assert.equal(pinned.manifest,'tests/oracle/manifest.json');
assert.ok(pinned.projectArguments.includes('--singleThreaded'));
assert.throws(()=>loadOracleProfile('ts8'),/Unregistered/);
assert.throws(()=>loadOracleProfile('../ts7'),/Unsafe/);
assert.throws(()=>loadOracleProfile(''),/Unsafe/);
const manifest=JSON.parse(readFileSync(resolve(root,pinned.manifest),'utf8'));
assert.equal(manifest.oracleVersion,pinned.version);
assert.equal(manifest.schemaVersion,1);
assert.ok(manifest.projects.some(item=>item.id==='scanner-ascii' && !item.expectDiagnostics));
console.log('PASS: explicit pinned CLI oracle profiles, unknown-version rejection, lexical acceptance fixture');
