// Pure Boolean logical operators retain exact singleton or wide facts.
const a = true && false;
const b = false || true;
const c = !!true && (!false || false);
let gate: boolean = false;
gate = 2 < 3;
const d = gate && false;
const e = gate || true;
const f = gate && gate;
const g = gate || gate;
const h = true && gate;
const i = false || gate;
const j = gate && true;
const k = gate || false;
const l = false && gate;
const m = true || gate;
const testA = a === false;
const testB = b === true;
const testC = c === true;
const testD = d !== false;
const testE = e === true;
const testF = f === true;
const testG = g !== false;
const testH = h === true;
const testI = i === false;
const testJ = j !== false;
const testK = k === true;
const testL = l === false;
const testM = m === true;
