let count: number = 1;
count = 2;
const sameCount: boolean = count === 2;
count = 1 + 2;
const broadCount: boolean = count === 9;
let label: string = "old";
label = "new";
const sameLabel: boolean = label === "new";
let ready: boolean = false;
ready = true;
const sameReady: boolean = ready === true;
